import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

function computeColumnWidths(data) {
  const colCount = data[0]?.length || 0;
  const widths = Array(colCount).fill(10);

  for (let c = 0; c < colCount; c += 1) {
    let maxWidth = 10;
    for (let r = 0; r < data.length; r += 1) {
      const value = data[r][c];
      const len = String(value ?? '').length;
      if (len > maxWidth) maxWidth = Math.min(len + 2, 40);
    }
    widths[c] = { wch: maxWidth };
  }

  return widths;
}

function styleHeaderRow(ws, rowIndex = 0, fillColor = '1A73E8', textColor = 'FFFFFFFF') {
  const range = XLSX.utils.decode_range(ws['!ref']);
  for (let C = range.s.c; C <= range.e.c; C += 1) {
    const address = XLSX.utils.encode_cell({ r: rowIndex, c: C });
    const cell = ws[address];
    if (cell) {
      cell.s = {
        font: { bold: true, color: { rgb: textColor } },
        fill: { fgColor: { rgb: fillColor } },
        alignment: { horizontal: 'center', vertical: 'center' },
        border: {
          top: { style: 'thin', color: { rgb: 'DADCE0' } },
          bottom: { style: 'thin', color: { rgb: 'DADCE0' } },
          left: { style: 'thin', color: { rgb: 'DADCE0' } },
          right: { style: 'thin', color: { rgb: 'DADCE0' } },
        },
      };
    }
  }
}

function applyWorksheetDefaults(ws, tabColor) {
  ws['!cols'] = ws['!cols'] || [];
  ws['!freeze'] = { xSplit: 0, ySplit: 1, topLeftCell: 'A2' };
  if (tabColor) ws['!tabColor'] = { rgb: tabColor.replace('#', '') };
}

export function buildOutputWorkbook(dataset1, dataset2, reconcileResults, sheet1Name, sheet2Name) {
  const workbook = XLSX.utils.book_new();

  const headers1 = dataset1.length > 0 ? Object.keys(dataset1[0]).filter(key => key !== '__recon_key') : [];
  const headers2 = dataset2.length > 0 ? Object.keys(dataset2[0]).filter(key => key !== '__recon_key') : [];

  const sheet1Data = [
    ['Reconciliation Key', ...headers1],
    ...dataset1.map((row) => [row.__recon_key, ...headers1.map((header) => row[header])]),
  ];
  const ws1 = XLSX.utils.aoa_to_sheet(sheet1Data);
  ws1['!cols'] = computeColumnWidths(sheet1Data);
  styleHeaderRow(ws1, 0, '1A73E8');
  applyWorksheetDefaults(ws1, '#1A73E8');
  XLSX.utils.book_append_sheet(workbook, ws1, 'Sheet 1 Data');

  const sheet2Data = [
    ['Reconciliation Key', ...headers2],
    ...dataset2.map((row) => [row.__recon_key, ...headers2.map((header) => row[header])]),
  ];
  const ws2 = XLSX.utils.aoa_to_sheet(sheet2Data);
  ws2['!cols'] = computeColumnWidths(sheet2Data);
  styleHeaderRow(ws2, 0, '1A73E8');
  applyWorksheetDefaults(ws2, '#1A73E8');
  XLSX.utils.book_append_sheet(workbook, ws2, 'Sheet 2 Data');

  const metadata = `Generated by DataRecon · ${new Date().toISOString()} · Sheet 1: ${sheet1Name} · Sheet 2: ${sheet2Name}`;
  const resultsHeader = ['Unique Key', 'Sheet 1 Match', 'Sheet 2 Match', 'Status'];
  const sheet3Data = [
    [metadata, '', '', ''],
    ['', '', '', ''],
    resultsHeader,
    ...reconcileResults.map((row) => [row.uniqueKey, row.sheet1Match, row.sheet2Match, row.status]),
  ];
  const ws3 = XLSX.utils.aoa_to_sheet(sheet3Data);
  ws3['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 1, c: 3 } }];
  ws3['!cols'] = computeColumnWidths(sheet3Data);
  styleHeaderRow(ws3, 2, '0D47A1');
  applyWorksheetDefaults(ws3, '#0D47A1');
  XLSX.utils.book_append_sheet(workbook, ws3, 'Reconciliation Results');

  return workbook;
}

export function downloadWorkbook(workbook, filename) {
  const workbookArray = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([workbookArray], { type: 'application/octet-stream' });
  saveAs(blob, filename);
  return blob.size;
}
